Feat/refactoring_v0.40
CMInformatik/cmi-grafana-monitoring pull request #39
Opened 2024-03-01 15:31 UTC by Noahnc

2024-03-04 09:49 UTC, Noahnc commented
PR darf nicht gemerged werden bovor nicht alle Agents angepasst sind.

2024-03-04 15:27 UTC, EliaSaSe requested changes

2024-03-04 15:27 UTC, EliaSaSe commented on modules/grafana_agent_uplink/README.md
> +Bei dieser Komponente handelt es sich in erster Linie um eine eins zu eins Kopie des folgenden Moduls: Grafana-Cloud-Autoconfigure Die einzige Modifikation, die wir am Modul vorgenommen haben, ist de
Netrics-Referenz entfernen.

2024-03-04 15:27 UTC, EliaSaSe commented on modules/grafana_filtering/README.md
> +## Argumente
Indent für Kapitel.

2024-03-04 15:27 UTC, EliaSaSe commented on modules/opentelemetry_receiver/README.md
> +Zum aktuellen Zeitpunkt exportiert die receiver Komponente keine Werte.
```suggestion
Zum aktuellen Zeitpunkt exportiert die Receiver-Komponente keine Werte.
```

2024-03-04 15:28 UTC, EliaSaSe commented
Local Dev-Enviroment kompatibel machen.

2024-03-05 09:05 UTC, EliaSaSe approved these changes

2024-03-05 09:05 UTC, merged